version: 2.1

jobs:

  commands:
    destroy_environment:
      steps:
        - run:
            name: Destroy Environment
            command: |
              aws cloudformation delete-stack --stack-name prod-${CIRCLE_WORKFLOW_ID}
  
  create_infrastructure:
    docker:
      - image: amazon/aws/cli
    steps:
      - checkout
      - run:
         name: Ensure backend infrastructure exist
         command: |
           aws cloudformation deploy \
            --template-file template.yml \
            --stack-name prod-${CIRCLE_WORKFLOW_ID}
      - run: return 1
      - destroy_environment
        when: on_fail

workflows:
  my_workflow:
    jobs:
      - create_infrastructure
