version: 2.1

jobs:
  create_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
        environment:
          ANSIBLE_HOST_KEY_CHECKING: False
    steps:
      - checkout
      - add_ssh_keys:
         fingerprints: ["1c:d3:72:de:8a:c3:b4:84:bd:3a:ba:ef:6d:89:6f:aa"]
      - run:
         name: Install dependencies
         command: |
           apk add --update ansible
      - run:
         name: Configure server
         command: |
           ansible-playbook -i inventory.txt playbook.yml

workflows:
  my_workflow:
    jobs:
      - create_infrastructure
