version: 2.1

jobs:
  
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
         fingerprints: ["1c:d3:72:de:8a:c3:b4:84:bd:3a:ba:ef:6d:89:6f:aa"]
      - run:
         name: Install dependencies
         command: |
           apk add --update ansible
      - run:
         name: Configure server
         command: |
           ansible-playbook -i inventory.txt playbook.yml

  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - run: apk add --update curl
      - run:
          name: smoke test
          command: |
            URL="18.236.221.236:3000"
            if curl -s --head ${URL} 
            then
             return 0
            else
             return 1
            fi

workflows:
  my_workflow:
    jobs:
      - configure_infrastructure
      - smoke_test:
         requires:
           - configure_infrastructure
